# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'XpmSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XpmSample
  pod 'XamarinPlatformMessaging', :path => "~/xpm/ios/"

end

target 'XpmSampleLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XpmSampleLib
  pod 'XamarinPlatformMessaging', :path => "~/xpm/ios/"

end
